apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-vol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-vol
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume-vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume-vol
      persistentVolumeClaim:
        claimName: csi-pvc-vol
